quadratic equation: Headers.h File Reference
Headers.h File Reference
Enumerations
enum spectrum { ZERO_ROOTS , ONE_ROOT , TWO_ROOTS , SS_INFINITY_ROOTS = -1 }
Functions
void Inputer (double *a, double *b, double *c)
Data entry.
int Dispatcher (double a, double b, double c, double *x1, double *x2)
Distributor for linear and quadratic equations.
int LineSolver (double b, double c, double *x1, double *x2)
Solves a linear equation and gives the output number of roots.
int SquareSolver (double a, double b, double c, double *x1, double *x2)
Solves a quadratic equation and gives the output number of roots.
void Outputer (int nRoots, double x1, double x2)
Produces output.
bool IsZero (double val)
Checks double error.
Variables
const int EPSILON = 0.1e-10
Error constant double.
Enumeration Type Documentation
spectrum
enum spectrum
Enumerator
ZERO_ROOTS
Number of equation roots: 0.
ONE_ROOT
Number of equation roots: 1.
TWO_ROOTS
Number of equation roots: 2.
SS_INFINITY_ROOTS
Number of equation roots: 0 INFINITY.
Definition at line 6 of file Headers.h.
{
    ZERO_ROOTS,
    ONE_ROOT,
    TWO_ROOTS,
    SS_INFINITY_ROOTS = -1
};
Function Documentation
Dispatcher()
int Dispatcher (double a, double b, double c, double * x1, double * x2)
Distributor for linear and quadratic equations.
Distributor for linear and quadratic equations.
Parameters
[in] a Coefficient before the quadratic term
[in] b Coefficient before the first degree term
[in] c Free term of the equation
[in] x1 First root of the equation
[in] x2 Second root of the equation
Definition at line 60 of file lesson1.cpp.
{
    assert(isfinite (a));
    assert(isfinite (b));
    assert(isfinite (c));
    assert(x1 != x2);
    assert(x1 != NULL);
    assert(x2 != NULL);
    if (IsZero(a))
        return LineSolver (b, c, x1, x2);
    else
        return SquareSolver (a, b, c, x1, x2);
}
References IsZero(), LineSolver(), and SquareSolver().
Referenced by main(), and UniversalTest().
Inputer()
void Inputer (double * a, double * b, double * c)
Data entry.
Data entry.
Parameters
[in] a Coefficient before the quadratic term
[in] b Coefficient before the first degree term
[in] c Free term of the equation
Definition at line 37 of file lesson1.cpp.
{
    assert(a != NULL);
    assert(b != NULL);
    assert(c != NULL);
    printf ("Ваше уравнение имеет вид:\na * x ^ 2 + b * x + c\n");
    printf ("Введите коэффициенты уравнения.\n\n");
    printf ("A   B   C\n");
    scanf ("%lg %lg %lg", a, b, c);                                                 // Entering odds from the keyboard
}
IsZero()
bool IsZero (double val)
Checks double error.
Parameters
[in] val Value of the input double variable
Definition at line 190 of file lesson1.cpp.
{
    assert (isfinite (val));
    if (EPSILON >= fabs (val))
        return true;
    return false;
}
References EPSILON.
Referenced by Dispatcher(), LineSolver(), and SquareSolver().
LineSolver()
int LineSolver (double b, double c, double * x1, double * x2)
Solves a linear equation and gives the output number of roots.
Parameters
[in] b Coefficient before the first degree term
[in] c Free term of the equation
[in] x1 First root of the equation
[in] x2 Second root of the equation
Definition at line 84 of file lesson1.cpp.
{
    assert(isfinite (b));
    assert(isfinite (c));
    assert(x1 != x2);
    assert(x1 != NULL);
    assert(x2 != NULL);
    if (IsZero(b))                                                                   // If b == 0
        return (IsZero(c))? SS_INFINITY_ROOTS : ZERO_ROOTS;
    else                                                                             // If b != 0
    {
        *x1 = *x2 = (-c / b);
        return ONE_ROOT;
    }
}
References IsZero(), ONE_ROOT, SS_INFINITY_ROOTS, and ZERO_ROOTS.
Referenced by Dispatcher().
Outputer()
void Outputer (int rootsQuantity, double x1, double x2)
Produces output.
Parameters
[in] rootsQuantity Number of roots of the equation
[in] x1 First root of the equation
[in] x2 Second root of the equation
Definition at line 148 of file lesson1.cpp.
{
    assert(isfinite (x1));
    assert(isfinite (x2));
    switch (rootsQuantity)
    {
        case ZERO_ROOTS:                                                            // If there are no roots
        {
            printf ("No roots!");
            break;
        }
        case ONE_ROOT:                                                              // One root
        {
            printf ("x = %g", x1);
            break;
        }
        case TWO_ROOTS:                                                             // Two roots
        {
            printf ("x1 = %lg, x2 = %lg", x1, x2);
            break;
        }
        case SS_INFINITY_ROOTS:                                                     // Infinite number of roots
        {
            printf ("Infinity roots.");
            break;
        }
        default:                                                                    // Something went wrong; no roots like 0/1/2/INF
        {
            printf ("main (): ERROR, there is %d roots://", rootsQuantity);
            break;
        }
    }
}
References ONE_ROOT, SS_INFINITY_ROOTS, TWO_ROOTS, and ZERO_ROOTS.
Referenced by main().
SquareSolver()
int SquareSolver (double a, double b, double c, double * x1, double * x2)
Solves a quadratic equation and gives the output number of roots.
Parameters
[in] a Coefficient before the quadratic term
[in] b Coefficient before the first degree term
[in] c Free term of the equation
[in] x1 First root of the equation
[in] x2 Second root of the equation
Definition at line 111 of file lesson1.cpp.
{
    assert(isfinite (a));
    assert(isfinite (b));
    assert(isfinite (c));
    assert(x1 != x2);
    assert(x1 != NULL);
    assert(x2 != NULL);
    double discriminant = b * b - 4 * a * c;                                        // Calculate the discriminant
    if (discriminant <= 0)                                                          // Testing for non-negative discriminant
        return ZERO_ROOTS;
    double sqrtDiscriminant = sqrt(discriminant);                                   // Root of the discriminant
    if (IsZero(sqrtDiscriminant))                                                   // One root
    {
        *x1 = *x2 = -b / (2 * a);
        return ONE_ROOT;
    }
    else                                                                            // 2 roots, sqrt_discriminant > EPSILAN
    {
        *x1 = (-b + sqrtDiscriminant) / (2 * a);                                    // First root
        *x2 = (-b - sqrtDiscriminant) / (2 * a);                                    // Second root
        return TWO_ROOTS;
    }
}
References IsZero(), ONE_ROOT, TWO_ROOTS, and ZERO_ROOTS.
Referenced by Dispatcher().
Variable Documentation
EPSILON
const int EPSILON = 0.1e-10
Error constant double.
Definition at line 14 of file Headers.h.
Referenced by IsZero().