quadratic equation: InputOutput.cpp File Reference
InputOutput.cpp File Reference
Functions
void Inputer (struct Coefficient *parameters)
Performs data entry.
void Outputer (struct Roots decision)
Produces output.
Function Documentation
Inputer()
void Inputer (struct Coefficient * parameters)
Performs data entry.
Data entry
Parameters
[in] a Coefficient before the quadratic term
[in] b Coefficient before the first degree term
[in] c Free term of the equation
Definition at line 12 of file InputOutput.cpp.
{
    assert (parameters != NULL);
    printf ("Your equation is:\na * x ^ 2 + b * x + c\n");
    printf ("Enter the coefficients of the equation.\n\n");
    printf ("A   B   C\n");
    while (scanf ("%lg %lg %lg", &parameters->a,                                  // Check, what kind of data User input
                                 &parameters->b,
                                 &parameters->c) != 3)
    {
        printf ("Oh no! You entered incorrect data.\n");
        printf ("Please, put coefficients, not chars.\n");
        BufferCleaner();                                                            // Clean Buffer
    }
    return;
}
References Coefficient::a, Coefficient::b, BufferCleaner(), and Coefficient::c.
Referenced by RunSolver().
Outputer()
void Outputer (struct Roots decision)
Produces output.
Data output.
Parameters
[in] rootsQuantity Number of roots of the equation
[in] x1 First root of the equation
[in] x2 Second root of the equation
Definition at line 40 of file InputOutput.cpp.
{
    assert (isfinite (decision.x1));
    assert (isfinite (decision.x2));
    switch (decision.nRoots)
    {
        case ZERO_ROOTS:                                                            // If there are no roots
        {
            printf ("No roots!");
            break;
        }
        case ONE_ROOT:                                                              // One root
        {
            printf ("x = %g", decision.x1);
            break;
        }
        case TWO_ROOTS:                                                             // Two roots
        {
            printf ("x1 = %lg, x2 = %lg", decision.x1, decision.x2);
            break;
        }
        case SS_INFINITY_ROOTS:                                                     // Infinite number of roots
        {
            printf ("Infinity roots.");
            break;
        }
        default:                                                                    // Something went wrong; no roots like 0/1/2/INF
        {
            printf ("main (): ERROR, there is %d roots://", decision.nRoots);
            break;
        }
    }
}
References Roots::nRoots, ONE_ROOT, SS_INFINITY_ROOTS, TWO_ROOTS, Roots::x1, Roots::x2, and ZERO_ROOTS.
Referenced by RunSolver().