SquareSolver: Menu.cpp File Reference
Menu.cpp File Reference
Functions
void Menu (int argc, char *argv[])
Choose, what User want`s to do (No parameters).
Function Documentation
Menu()
void Menu (int argc, char * argv[])
Choose, what User want`s to do (No parameters).
Choose, what User want`s to do (No parameters)
Definition at line 9 of file Menu.cpp.
{
    assert (argc >= 1);
    assert (argv != NULL);
    if (argc > 1)
    {
        switch (StringCompare (argv[1]))
        {
            case TEST:
            {
                StartTests ();
            }
            case PUT:
            {
                RunSolver ();
            }
            case HELP:
            {
                HelpList ();
            }
        }
    }
    else
    {
        RunSolver ();
    }
}
References HELP, HelpList(), PUT, RunSolver(), StartTests(), StringCompare(), and TEST.
Referenced by main().