SquareSolver: Menu.h File Reference
Menu.h File Reference
Functions
void Menu (int argc, char *argv[])
Choose, what User want`s to do (No parameters)
void RunSolver ()
Run Square Solver.
void StartTests ()
Start Tests.
int TestOrPut ()
User choose.
int GetFlags (char *str)
void HelpList ()
Function Documentation
GetFlags()
int GetFlags (char * str)
HelpList()
void HelpList ()
Definition at line 105 of file Utils.cpp.
{
    printf ("This program solve`s quadratic equations.\nFor more infomation watch README.md/n/n");
    printf ("--test (-t) - For  test program\n\n");
    printf ("--put (-p) - For put Your values\n\n");
    printf ("--help (-h) - For help-list\n\n");
}
Referenced by Menu().
Menu()
void Menu (int argc, char * argv[])
Choose, what User want`s to do (No parameters)
Choose, what User want`s to do (No parameters)
Definition at line 9 of file Menu.cpp.
{
    assert (argc >= 1);
    assert (argv != NULL);
    if (argc > 1)
    {
        switch (StringCompare (argv[1]))
        {
            case TEST:
            {
                StartTests ();
            }
            case PUT:
            {
                RunSolver ();
            }
            case HELP:
            {
                HelpList ();
            }
        }
    }
    else
    {
        RunSolver ();
    }
}
References HELP, HelpList(), PUT, RunSolver(), StartTests(), StringCompare(), and TEST.
Referenced by main().
RunSolver()
void RunSolver ()
Run Square Solver.
Definition at line 9 of file Solvers.cpp.
{
    Coefficient parameters {};
    Roots decision {};
    Inputer (&parameters);                                                                  // Gets equation coefficients
    Dispatcher (parameters, &decision);                                                     // Solve the equation
    Outputer (decision);                                                                    // Output results
}
References Dispatcher(), Inputer(), and Outputer().
Referenced by Menu().
StartTests()
void StartTests ()
Start Tests.
Start Tests.
Definition at line 41 of file Tests.cpp.
{
    int rightTests = 0;
    int falseTests = 6;
    TestRes data[QUANTITY] =
    {
        {{ 1,      2,     -3   }, { 1,    -3,   2}},
        {{ 5,      0,      0   }, { 0,     0,   1}},
        {{ 0,      5,     -3   }, { 0.6,   0.6, 1}},
        {{ 0.25, -25,      0   }, { 0,     100, 2}},
        {{ 0.1,    0.999, -0.01}, { 0.01, -10,  2}},
        {{-1,      66,    -128 }, { 2,     64,  2}}
    };
    for (int testNum = 0; testNum <= HOWTEST; testNum++)
    {
        rightTests += UniversalTest (testNum, data[testNum].parameters, data[testNum].decision);
    }
    printf ("\n"
            "There are/is %d right test(s).\n", rightTests);
    printf ("There are/is %d wrong test(s).\n", (falseTests - rightTests));
}
References HOWTEST, QUANTITY, and UniversalTest().
Referenced by Menu().
TestOrPut()
int TestOrPut ()
User choose.
User choose.
Definition at line 48 of file Utils.cpp.
{
    int ch1 = 0;
    int ch2 = 0;
    while (true)
    {
        ch1 = getchar ();
        if (ch1 != 't' && ch1 != 'p')
        {
            BufferCleaner();
            printf ("Watch out! You input wrong data. Shut up and read Kernighan and Ritchie!!!\n");
        }
        else if ((ch2 = getchar ()) != '\n' && ch2 != EOF)
        {
            BufferCleaner();
            printf ("Watch out! You input wrong data. Shut up and read Kernighan and Ritchie!!!\n");
        }
        else
        {
            return ch1;
        }
    }
}
References BufferCleaner().