quadratic equation: Solvers.h File Reference
Solvers.h File Reference
Data Structures
struct Coefficient
< Coefficients
struct Roots
< Roots
Enumerations
enum spectrum { ZERO_ROOTS , ONE_ROOT , TWO_ROOTS , SS_INFINITY_ROOTS = -1 }
Functions
void Dispatcher (struct Coefficient parameters, struct Roots *docision)
Distributor for linear and quadratic equations.
void LineSolver (double b, double c, struct Roots *dicision)
Solve linear equations.
void SquareSolver (struct Coefficient parameters, struct Roots *docision)
Solving a quadratic equation
void RunSolver ()
Start soling.
int TestOrPut ()
Function, where User choose test or put.
Variables
const double EPSILON = 1e-10
Error constant double.
Enumeration Type Documentation
spectrum
enum spectrum
Enumerator
ZERO_ROOTS
Number of equation roots: 0.
ONE_ROOT
Number of equation roots: 1.
TWO_ROOTS
Number of equation roots: 2.
SS_INFINITY_ROOTS
Number of equation roots: 0 INFINITY.
Definition at line 27 of file Solvers.h.
{
    ZERO_ROOTS,
    ONE_ROOT,
    TWO_ROOTS,
    SS_INFINITY_ROOTS = -1
};
Function Documentation
Dispatcher()
void Dispatcher (struct Coefficient parameters, struct Roots * decision)
Distributor for linear and quadratic equations.
Distributor for linear and quadratic equations.
Parameters
[in] parameters Struct with coefficient of equation
[in] decision Struct with roots
Definition at line 27 of file Solvers.cpp.
{
    assert (isfinite (parameters.a));
    assert (isfinite (parameters.b));
    assert (isfinite (parameters.c));
    assert (decision != NULL);
    if (IsZero (parameters.a))
        LineSolver (parameters.b, parameters.c, decision);
    else
        SquareSolver (parameters, decision);
}
References Coefficient::a, Coefficient::b, Coefficient::c, IsZero(), LineSolver(), and SquareSolver().
Referenced by RunSolver(), and UniversalTest().
LineSolver()
void LineSolver (double b, double c, struct Roots * decision)
Solve linear equations.
Solve linear equations.
Parameters
[in] b Coefficient before the first degree term
[in] c Free term of the equation
[in] decision Struct with roots
Definition at line 48 of file Solvers.cpp.
{
    assert (isfinite (b));
    assert (isfinite (c));
    assert (decision != NULL);
    if (IsZero (b))
    {
        if (IsZero (c))
        {
            decision->nRoots = SS_INFINITY_ROOTS;
        }
        else
        {
            decision->nRoots = ZERO_ROOTS;
        }
        return;
    }
    else
    {
        decision->x1 = decision->x2 = (-c / b);
        decision->nRoots = ONE_ROOT;
        return;
    }
}
References IsZero(), Roots::nRoots, ONE_ROOT, SS_INFINITY_ROOTS, Roots::x1, Roots::x2, and ZERO_ROOTS.
Referenced by Dispatcher().
RunSolver()
void RunSolver ()
Start soling.
Start soling.
Definition at line 8 of file Solvers.cpp.
{
    Coefficient parameters {};
    Roots decision {};
    Inputer (&parameters);                                                                  // Gets equation coefficients
    Dispatcher (parameters, &decision);                                                     // Solve the equation
    Outputer (decision);                                                                    // Output results
}
SquareSolver()
void SquareSolver (struct Coefficient parameters, struct Roots * decision)
Solving a quadratic equation
Solving a quadratic equation
Parameters
[in] parameters Struct with coefficient before the quadratic term
[in] decision Struct with roots of quadratic term
Definition at line 82 of file Solvers.cpp.
{
    assert (isfinite (parameters.a));
    assert (isfinite (parameters.b));
    assert (isfinite (parameters.c));
    assert (decision != NULL);
    if (IsZero (parameters.c))                                                               // If c == 0
    {
        if (IsZero (parameters.b))
        {
            decision->x1 = decision->x2 = 0;
            decision->nRoots = ONE_ROOT;
            return;
        }
        decision->x1 = 0;
        decision->x2 = (parameters.b / -parameters.a);
        decision->nRoots = TWO_ROOTS;
        return;
    }
    double discriminant = parameters.b * parameters.b - 4 * parameters.a * parameters.c;    // Calculate the discriminant
    if (discriminant <= -EPSILON)                                                           // Testing for non-negative discriminant
    {
        decision->nRoots = ZERO_ROOTS;
        return;
    }
    double sqrtDiscriminant = sqrt (discriminant);                                           // Root of the discriminant
    if (IsZero (sqrtDiscriminant))                                                           // One root
    {
        decision->x1 = decision->x2 = (-parameters.b / parameters.a);
        decision->nRoots = ONE_ROOT;
        return;
    }
    else                                                                                    // 2 roots, sqrt_discriminant > EPSILAN
    {
        decision->x1 = (-parameters.b + sqrtDiscriminant) / (2 * parameters.a);           // First root
        decision->x2 = (-parameters.b - sqrtDiscriminant) / (2 * parameters.a);           // Second root
        decision->nRoots = TWO_ROOTS;
        return;
    }
}
References Coefficient::a, Coefficient::b, Coefficient::c, EPSILON, IsZero(), Roots::nRoots, ONE_ROOT, TWO_ROOTS, Roots::x1, Roots::x2, and ZERO_ROOTS.
Referenced by Dispatcher().
TestOrPut()
int TestOrPut ()
Function, where User choose test or put.
Function, where User choose test or put.
User choose.
Definition at line 48 of file Utils.cpp.
{
    int ch1 = 0;
    int ch2 = 0;
    while (true)
    {
        ch1 = getchar ();
        ch2 = getchar ();
        if (ch1 == 't' && ch2 == '\n')
        {
            return TEST;
        }
        else if (ch1 == 'p' && ch2 == '\n')
        {
            return PUT;
        }
        else
        {
            if (ch1 != '\n' && ch2 != '\n')
            {
                BufferCleaner();
                printf ("Watch out! You input wrong data. Shut up and read Kernighan and Ritchie!!!\n");
            }
        }
    }
}
Variable Documentation
EPSILON
const double EPSILON = 1e-10
Error constant double.
Definition at line 35 of file Solvers.h.
Referenced by IsZero(), and SquareSolver().