SquareSolver: Tests.h File Reference
Tests.h File Reference
Data Structures
struct TestRes
struct TestConst
Functions
void StartTests ()
Start solving equation.
int UniversalTest (int testNum, struct Coefficient parameters, struct Roots decision)
Function for unit tests.
Variables
const int QUANTITY = 6
Size of array with tests.
const int HOWTEST = 5
Numbers of tests.
Function Documentation
StartTests()
void StartTests ()
Start solving equation.
Start solving equation.
Start Tests.
Definition at line 41 of file Tests.cpp.
{
    int rightTests = 0;
    int falseTests = 6;
    TestRes data[QUANTITY] =
    {
        {{ 1,      2,     -3   }, { 1,    -3,   2}},
        {{ 5,      0,      0   }, { 0,     0,   1}},
        {{ 0,      5,     -3   }, { 0.6,   0.6, 1}},
        {{ 0.25, -25,      0   }, { 0,     100, 2}},
        {{ 0.1,    0.999, -0.01}, { 0.01, -10,  2}},
        {{-1,      66,    -128 }, { 2,     64,  2}}
    };
    for (int testNum = 0; testNum <= HOWTEST; testNum++)
    {
        rightTests += UniversalTest (testNum, data[testNum].parameters, data[testNum].decision);
    }
    printf ("\n"
            "There are/is %d right test(s).\n", rightTests);
    printf ("There are/is %d wrong test(s).\n", (falseTests - rightTests));
}
UniversalTest()
int UniversalTest (int testNum, struct Coefficient parameters, struct Roots decision)
Function for unit tests.
Parameters
[in] testNum Number of the test
[in] parameters Struct with coefficient of equation
[in] decision Struct with roots
Definition at line 12 of file Tests.cpp.
{
    TestConst expected = {decision.nRoots, decision.x1, decision.x2};
    Dispatcher (parameters, &decision);
    if (expected.nRoots != decision.nRoots ||
        !DoubleComparison (expected.x1Required, decision.x1) ||
        !DoubleComparison (expected.x2Required, decision.x2))
    {
        printf ("\n"
                "ERROR, Test number %d\n", testNum);
        printf ("Input Data: a = %lg, b = %lg, c = %lg\n", parameters.a, parameters.b, parameters.c);
        printf ("Expacted Data: x1 = %lg, x2 = %lg, nRoots = %d\n", expected.x1Required, expected.x2Required, expected.nRoots);
        printf ("Received Data: x1 = %lg, x2 = %lg, nRoots = %d\n", decision.x1, decision.x2, decision.nRoots);
        return 0;
    }
    else
    {
        printf ("Nice! Test number %d is fine!\n", testNum);
        return 1;
    }
}
References Coefficient::a, Coefficient::b, Coefficient::c, Dispatcher(), DoubleComparison(), Roots::nRoots, TestConst::nRoots, Roots::x1, TestConst::x1Required, Roots::x2, and TestConst::x2Required.
Referenced by StartTests().
Variable Documentation
HOWTEST
const int HOWTEST = 5
Numbers of tests.
Definition at line 15 of file Tests.h.
Referenced by StartTests().
QUANTITY
const int QUANTITY = 6
Size of array with tests.
Definition at line 14 of file Tests.h.
Referenced by StartTests().