SquareSolver: Utils.cpp File Reference
Utils.cpp File Reference
Functions
bool IsZero (double val)
Checks double error.
bool DoubleComparison (double firstNum, double secondNum)
Compearing two double nums.
void BufferCleaner ()
Clean buffer.
int TestOrPut ()
Return what user want: test or put vals.
int StringCompare (char *str)
void HelpList ()
Function Documentation
BufferCleaner()
void BufferCleaner ()
Clean buffer.
Buffer cleaner.
Definition at line 37 of file Utils.cpp.
{
    int ch = 0;
    while ((ch == getchar ()) != '\n' && ch != EOF) {}
}
Referenced by Inputer(), and TestOrPut().
DoubleComparison()
bool DoubleComparison (double firstNum, double secondNum)
Compearing two double nums.
Checking equality double.
Parameters
[in] firstNum First double num
[in] secondNum Second double num
Definition at line 25 of file Utils.cpp.
{
    assert (isfinite (firstNum));
    assert (isfinite (secondNum));
    return IsZero (firstNum - secondNum);
}
References IsZero().
Referenced by UniversalTest().
HelpList()
void HelpList ()
Definition at line 105 of file Utils.cpp.
{
    printf ("This program solve`s quadratic equations.\nFor more infomation watch README.md/n/n");
    printf ("--test (-t) - For  test program\n\n");
    printf ("--put (-p) - For put Your values\n\n");
    printf ("--help (-h) - For help-list\n\n");
}
Referenced by Menu().
IsZero()
bool IsZero (double val)
Checks double error.
Double error check.
Parameters
[in] val Value of the input double variable
Definition at line 10 of file Utils.cpp.
{
    assert (isfinite (val));
    if (EPSILON >= fabs (val))
        return true;
    return false;
}
References EPSILON.
Referenced by Dispatcher(), DoubleComparison(), LineSolver(), and SquareSolver().
StringCompare()
int StringCompare (char * str)
Definition at line 75 of file Utils.cpp.
{
    int lenStr = strlen(str);
    if (lenStr == 2 && str[0] == '-')
    {
        return str[SYMB]; // if str[symb] == 'q'
    }
    else if (strlen(str) <= 6)
    {
        if (strcmp (str, "--test") == 0)
        {
            return TEST;
        }
        else if (strcmp (str, "--help") == 0)
        {
            return HELP;
        }
        else if (strcmp (str, "--put") == 0)
        {
            return PUT;
        }
    }
    else
    {
        printf ("You put something wrong, try again./n");
    }
}
References HELP, PUT, SYMB, and TEST.
Referenced by Menu().
TestOrPut()
int TestOrPut ()
Return what user want: test or put vals.
Function, where User choose test or put.
User choose.
Definition at line 48 of file Utils.cpp.
{
    int ch1 = 0;
    int ch2 = 0;
    while (true)
    {
        ch1 = getchar ();
        if (ch1 != 't' && ch1 != 'p')
        {
            BufferCleaner();
            printf ("Watch out! You input wrong data. Shut up and read Kernighan and Ritchie!!!\n");
        }
        else if ((ch2 = getchar ()) != '\n' && ch2 != EOF)
        {
            BufferCleaner();
            printf ("Watch out! You input wrong data. Shut up and read Kernighan and Ritchie!!!\n");
        }
        else
        {
            return ch1;
        }
    }
}
References BufferCleaner().