quadratic equation: Utils.h File Reference
Utils.h File Reference
Enumerations
enum spectrum1 { TEST = 0 , PUT = 1 }
Functions
bool IsZero (double val)
Double error check.
bool DoubleComparison (double firstNum, double secondNum)
Checking equality double.
void BufferCleaner ()
Buffer cleaner.
Enumeration Type Documentation
spectrum1
enum spectrum1
Enumerator
TEST
Test mode.
PUT
Put mode.
Definition at line 12 of file Utils.h.
{
    TEST = 0,
    PUT  = 1
};
Function Documentation
BufferCleaner()
void BufferCleaner ()
Buffer cleaner.
Buffer cleaner.
Definition at line 37 of file Utils.cpp.
{
    int ch = 0;
    while ((ch == getchar ()) != '\n' && ch != EOF){}
}
Referenced by Inputer(), and TestOrPut().
DoubleComparison()
bool DoubleComparison (double firstNum, double secondNum)
Checking equality double.
Checking equality double.
Parameters
[in] firstNum First double num
[in] secondNum Second double num
Definition at line 25 of file Utils.cpp.
{
    assert (isfinite (firstNum));
    assert (isfinite (secondNum));
    return IsZero (firstNum - secondNum);
}
References IsZero().
Referenced by UniversalTest().
IsZero()
bool IsZero (double val)
Double error check.
Double error check.
Parameters
[in] val Value of the input double variable
Definition at line 10 of file Utils.cpp.
{
    assert (isfinite (val));
    if (EPSILON >= fabs (val))
        return true;
    return false;
}
References EPSILON.
Referenced by Dispatcher(), DoubleComparison(), LineSolver(), and SquareSolver().